"""
Auto Rigger Attribute Widgets Aggregator
"""

from gt.tools.auto_rigger.attr_widgets.attr_widget_base import AttrWidgetCommon
from gt.tools.auto_rigger.attr_widgets.attr_widget_generic import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_generic_fk import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_root import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_ik_base import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_generic_ik import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_arm import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_attribute_hub import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_spine import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_head import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_biped_arm import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_quad_rear_leg import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_biped_leg import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_quad_front_leg import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_biped_finger import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_chain import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_ribbon_base import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_ribbon_generic import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_ribbon_quad_spine import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_socket import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_meta_human_face import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_piston import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_anim_mass_references import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_group import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_new_scene import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_import_file import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_skin_weights import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_ngskin import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_shapes_snapshot import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_export_skeletal_mesh import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_save_scene import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_capture_base import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_thumbnail_capture import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_playblast_capture import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_camera_setup import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_load_scene import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_rom_loader import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_enum_variants import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_picker_data import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_python import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_notes import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_corrective_base import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_corrective_generic import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_corrective_fk import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_rbf_load import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_probe import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_probe_distance import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_probe_rotation import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_collections import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_validation import *
from gt.tools.auto_rigger.attr_widgets.attr_widget_project import *
